apiVersion: apps/v1
kind: Deployment
metadata:
  name: Jeevan
  namespace: default
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-app-sha256-1
        image: asia-south1-docker.pkg.dev/inspiring-dryad-400607/mohan/todo-app:tagversion

