apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  namespace: default
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-app-sha256-1
        image: us-east1-docker.pkg.dev/jenkins-poc-400711/jenkins-repo/todo-app:tagversion

